# Capstone Project - 16BEM0002, 16BEM0068

### Title: Semantic Approach for Evaluation of Energy Storage Technologies under Fuzzy Environment

In [140]:
import numpy as np
import pandas as pd
lin_term_vikor={'VL':(0,0,0.1),'ML':(0.1,0.2,0.3),'M':(0.3,0.4,0.5),'MH':(0.5,0.6,0.7),'VH':(0.7,0.8,0.9),'I':(0.9,1,1)} # Linguistic Terminology for VIKOR
criteria={'Energy Density':('Mass Energy Density','Volume Energy Density'),'Life Cycles':('Number of discharge cycles','Shelf life'),'Cycle efficiency':('Output/Input','Time for unit Energy Storage'),'Investment Level':('Capital','Time'),'Suitability to climatic conditions':('Temperture','Humidity'),'Space required':('Floor Area','Volume occupied')} # Criteria and Sub-Criteria
alternatives=['Electrochemical','Electrical','Magnetic','Mechanical','Chemical'] # Alternatives
lin_term_anp=[(1,1,2),(1,2,3),(2,3,4),(3,4,5),(4,5,6),(5,6,7),(6,7,8),(7,8,9),(8,9,9)] # Linguistic Terminology for ANP
lin_term_dematel={'N':(0,0,0.1),'VL':(0,0.1,0.2),'L':(0.1,0.2,0.3),'FL':(0.2,0.3,0.4),'ML':(0.3,0.4,0.5),'M':(0.4,0.5,0.6),'MG':(0.5,0.6,0.7),'FG':(0.6,0.7,0.8),'G':(0.7,0.8,0.9),'VG':(0.8,0.9,1),'E':(0.9,1,1)} # Linguistic Terminology for DEMATEL
I=np.array([[1,0],[0,1]]) # Initialization of Identity Matrix
criteria_weights=[],
anp_term={'NA':(0,0,0),'EI':(1,1,2),'MI':(2,3,4),'SI':(4,5,6),'VSI':(6,7,8),'AI':(8,9,9),'1/EI':(1/2,1,1),'1/MI':(1/4,1/3,1/2),'1/SI':(1/6,1/5,1/4),'1/VSI':(1/8,1/7,1/6),'1/AI':(1/9,1/9,1/8)} # Linguistic Terminoligy for ANP

## Fuzzy Dematel

In [82]:
dematel_weights=[] # Initializaing list to store final DEMATEL weights
flag=0
for i in criteria.values():
    flag+=1
    X=[]
    a=np.array([[[0,0,0],0],[0,[0,0,0]]])
    l1=input(f'Enter ratings of {i[0]} wrt {i[1]}: ') # Taking user input for Sub-criteria v/s Sub-criteria sets
    l2=input(f'Enter ratings of {i[1]} wrt {i[0]}: ')
    a[0][1]=list(lin_term_dematel[l1.upper()])
    a[1][0]=list(lin_term_dematel[l2.upper()]) # Obtaining Fuzzy Direct Relation Matrix
    s=max(a[0][1][2],a[1][0][2]) # Performing computation
    a[0][1]=np.divide(a[0][1],s)
    a[1][0]=np.divide(a[1][0],s)
    l=np.array([a[i][j][0] for i in range(2) for j in range(2)])
    m=np.array([a[i][j][1] for i in range(2) for j in range(2)])
    u=np.array([a[i][j][2] for i in range(2) for j in range(2)])
    l=l.reshape(2,2)
    m=m.reshape(2,2)
    u=u.reshape(2,2)
    I_l,I_m,I_u=np.subtract(I,l),np.subtract(I,m),np.subtract(I,u)
    inv_l,inv_m,inv_u=np.linalg.inv(I_l),np.linalg.inv(I_m),np.linalg.inv(I_u)
    print(inv_l)
    print(inv_m)
    print(inv_u)
    l1,m1,u1=l.dot(inv_l),m.dot(inv_m),u.dot(inv_u)
    t_m1,t_m2=[],[]
    t_m1=[[l1[0][0],m1[0][0],u1[0][0]],[l1[1][0],m1[1][0],u1[1][0]]]
    t_m2=[[l1[0][1],m1[0][1],u1[0][1]],[l1[1][1],m1[1][1],u1[1][1]]]
    d1,d2=[],[]
    for j in range(2):
        d1.append((t_m1[j][0]+4*t_m1[j][1]+t_m1[j][2])/6)
        d2.append((t_m2[j][0]+4*t_m2[j][1]+t_m2[j][2])/6)
    d1.append(d1[0]+d1[1])
    d2.append(d2[0]+d2[1])
    inner=[[0,0],[0,0]]
    for j in range(2):
        inner[j]=[d1[j]/d1[2],d2[j]/d2[2]] # Obtain final DEMATEL Weights for each Sub-Criteria set
    dematel_weights.append(inner)

Enter ratings of Mass Energy Density wrt Volume Energy Density: fl
Enter ratings of Volume Energy Density wrt Mass Energy Density: m
[[1.28571429 0.42857143]
 [0.85714286 1.28571429]]
[[1.71428571 0.85714286]
 [1.42857143 1.71428571]]
[[3. 2.]
 [3. 3.]]
Enter ratings of Number of discharge cycles wrt Shelf life: e
Enter ratings of Shelf life wrt Number of discharge cycles: fl
[[1.2195122  1.09756098]
 [0.24390244 1.2195122 ]]
[[1.42857143 1.42857143]
 [0.42857143 1.42857143]]
[[1.66666667 1.66666667]
 [0.66666667 1.66666667]]
Enter ratings of Output/Input wrt Time for unit Energy Storage: n
Enter ratings of Time for unit Energy Storage wrt Output/Input: fl
[[1.  0. ]
 [0.5 1. ]]
[[1.   0.  ]
 [0.75 1.  ]]
[[1.33333333 0.33333333]
 [1.33333333 1.33333333]]
Enter ratings of Capital wrt Time: fl
Enter ratings of Time wrt Capital: e
[[1.2195122  0.24390244]
 [1.09756098 1.2195122 ]]
[[1.42857143 0.42857143]
 [1.42857143 1.42857143]]
[[1.66666667 0.66666667]
 [1.66666667 1.66666667]]
Enter 

In [83]:
dematel_weights

[[[0.34951456310679613, 0.5324675324675324],
  [0.6504854368932038, 0.4675324675324675]],
 [[0.4976661480328962, 0.7652793793898732],
  [0.5023338519671038, 0.23472062061012683]],
 [[0.06451612903225806, 0.5], [0.9354838709677419, 0.5]],
 [[0.23472062061012683, 0.5023338519671038],
  [0.7652793793898732, 0.49766614803289616]],
 [[0.47353019420058523, 0.7186215618084097],
  [0.5264698057994147, 0.28137843819159025]],
 [[0.4327294685990339, 0.5242963356346256],
  [0.5672705314009662, 0.4757036643653744]]]

# Fuzzy ANP

In [84]:
pairwise_matrix=np.ones([6,6],dtype=int) # Initializing Matrix
main_criteria=list(criteria.keys()) # Implementing fuzzy ANP for Criteria v/s Criteria, i.e. Outer Dependancy
pairwise_matrix=pd.DataFrame(pairwise_matrix,columns=main_criteria,index=main_criteria,dtype=object) # Creating Dataframe for pairwise comparision matrix
for j in range(6): # Reading user input
    for k in range(6):
        if(j==k):
            x=(1,1,1)
            pairwise_matrix[main_criteria[k]][main_criteria[j]]=x
        if(k>j):
            l=int(input(f'Enter rating {main_criteria[j]} wrt {main_criteria[k]}: '))-1
            x=lin_term_anp[l]
            pairwise_matrix[main_criteria[k]][main_criteria[j]]=x
            pairwise_matrix[main_criteria[j]][main_criteria[k]]=(1/x[2],1/x[1],1/x[0])
        
pairwise_matrix

Enter rating Energy Density wrt Life Cycles: 3
Enter rating Energy Density wrt Cycle efficiency: 3
Enter rating Energy Density wrt Investment Level: 1
Enter rating Energy Density wrt Suitability to climatic conditions: 7
Enter rating Energy Density wrt Space required: 9
Enter rating Life Cycles wrt Cycle efficiency: 3
Enter rating Life Cycles wrt Investment Level: 3
Enter rating Life Cycles wrt Suitability to climatic conditions: 5
Enter rating Life Cycles wrt Space required: 5
Enter rating Cycle efficiency wrt Investment Level: 1
Enter rating Cycle efficiency wrt Suitability to climatic conditions: 3
Enter rating Cycle efficiency wrt Space required: 5
Enter rating Investment Level wrt Suitability to climatic conditions: 5
Enter rating Investment Level wrt Space required: 7
Enter rating Suitability to climatic conditions wrt Space required: 1


Energy Density  \
Energy Density                                                              (1, 1, 1)   
Life Cycles                                           (0.25, 0.3333333333333333, 0.5)   
Cycle efficiency                                      (0.25, 0.3333333333333333, 0.5)   
Investment Level                                                      (0.5, 1.0, 1.0)   
Suitability to climatic conditions  (0.125, 0.14285714285714285, 0.16666666666666666)   
Space required                        (0.1111111111111111, 0.1111111111111111, 0.125)   

                                                         Life Cycles  \
Energy Density                                             (2, 3, 4)   
Life Cycles                                                (1, 1, 1)   
Cycle efficiency                     (0.25, 0.3333333333333333, 0.5)   
Investment Level                     (0.25, 0.3333333333333333, 0.5)   
Suitability to climatic conditions  (0.16666666666666666, 0.2, 0.25)   
Space required                      (0.16666666666666666, 0.2, 0.25)   

                                                    Cycle efficiency  \
Energy Density                                             (2, 3, 4)   
Life Cycles                                                (2, 3, 4)   
Cycle efficiency                                           (1, 1, 1)   
Investment Level                                     (0.5, 1.0, 1.0)   
Suitability to climatic conditions   (0.25, 0.3333333333333333, 0.5)   
Space required                      (0.16666666666666666, 0.2, 0.25)   

                                                                     Investment Level  \
Energy Density                                                              (1, 1, 2)   
Life Cycles                                                                 (2, 3, 4)   
Cycle efficiency                                                            (1, 1, 2)   
Investment Level                                                            (1, 1, 1)   
Suitability to climatic conditions                   (0.16666666666666666, 0.2, 0.25)   
Space required                      (0.125, 0.14285714285714285, 0.16666666666666666)   

                                   Suitability to climatic conditions  \
Energy Density                                              (6, 7, 8)   
Life Cycles                                                 (4, 5, 6)   
Cycle efficiency                                            (2, 3, 4)   
Investment Level                                            (4, 5, 6)   
Suitability to climatic conditions                          (1, 1, 1)   
Space required                                        (0.5, 1.0, 1.0)   

                                   Space required  
Energy Density                          (8, 9, 9)  
Life Cycles                             (4, 5, 6)  
Cycle efficiency                        (4, 5, 6)  
Investment Level                        (6, 7, 8)  
Suitability to climatic conditions      (1, 1, 2)  
Space required                          (1, 1, 1)

In [85]:
opt=0.5 # Defining Degree Optimism
matrix2=pairwise_matrix.copy()
for j in range(6): # Performing ANP Computations for Criteria v/s Criteria
    for k in range(6):
        x=matrix2[main_criteria[k]][main_criteria[j]]
        w=opt*x[2]+(1-opt)*x[0]
        matrix2[main_criteria[k]][main_criteria[j]]=w
total=list(matrix2.sum(axis=0)) 
matrix2
nor_matrix=matrix2.copy() # Pairwise Comparison Matrix for the Relative Importance of Criteria
nor_matrix

Energy Density Life Cycles  \
Energy Density                                  1           3   
Life Cycles                                 0.375           1   
Cycle efficiency                            0.375       0.375   
Investment Level                             0.75       0.375   
Suitability to climatic conditions       0.145833    0.208333   
Space required                           0.118056    0.208333   

                                   Cycle efficiency Investment Level  \
Energy Density                                    3              1.5   
Life Cycles                                       3                3   
Cycle efficiency                                  1              1.5   
Investment Level                               0.75                1   
Suitability to climatic conditions            0.375         0.208333   
Space required                             0.208333         0.145833   

                                   Suitability to climatic conditions  \
Energy Density                                                      7   
Life Cycles                                                         5   
Cycle efficiency                                                    3   
Investment Level                                                    5   
Suitability to climatic conditions                                  1   
Space required                                                   0.75   

                                   Space required  
Energy Density                                8.5  
Life Cycles                                     5  
Cycle efficiency                                5  
Investment Level                                7  
Suitability to climatic conditions            1.5  
Space required                                  1

In [86]:
nor_matrix=matrix2.copy()
max_eigen=0 # Initializing maximum eigen value
for j in range(6):
    for k in range(6):
        x=matrix2[main_criteria[k]][main_criteria[j]]/total[k]
        nor_matrix[main_criteria[k]][main_criteria[j]]=x
priority_vector=1/6*nor_matrix.sum(axis=1)
for j in range(len(total)):
    max_eigen+=total[j]*priority_vector[j] # Finding maximum eigen value
ci=(max_eigen-6)/5 # Calculating Consistency Index
cr=ci/1.24 # Defining Consistency Ratio
priority_vector=list(priority_vector)
nor_matrix # Normalized Relative Weights


Energy Density Life Cycles  \
Energy Density                           0.361809    0.580645   
Life Cycles                              0.135678    0.193548   
Cycle efficiency                         0.135678   0.0725806   
Investment Level                         0.271357   0.0725806   
Suitability to climatic conditions      0.0527638   0.0403226   
Space required                          0.0427136   0.0403226   

                                   Cycle efficiency Investment Level  \
Energy Density                                 0.36         0.203966   
Life Cycles                                    0.36         0.407932   
Cycle efficiency                               0.12         0.203966   
Investment Level                               0.09         0.135977   
Suitability to climatic conditions            0.045        0.0283286   
Space required                                0.025          0.01983   

                                   Suitability to climatic conditions  \
Energy Density                                               0.321839   
Life Cycles                                                  0.229885   
Cycle efficiency                                             0.137931   
Investment Level                                             0.229885   
Suitability to climatic conditions                           0.045977   
Space required                                              0.0344828   

                                   Space required  
Energy Density                           0.303571  
Life Cycles                              0.178571  
Cycle efficiency                         0.178571  
Investment Level                             0.25  
Suitability to climatic conditions      0.0535714  
Space required                          0.0357143

In [87]:
zero=np.zeros([19,19]) # Initializing Dataframe for Supermatrix
col=['Goal','C11','C12','C21','C22','C31','C32','C41','C42','C51','C52','C61','C62','C1','C2','C3','C4','C5','C6']
sm=pd.DataFrame(zero,columns=col, index=col,dtype=object)
list(sm.columns)
sm.index

Index(['Goal', 'C11', 'C12', 'C21', 'C22', 'C31', 'C32', 'C41', 'C42', 'C51',
       'C52', 'C61', 'C62', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6'],
      dtype='object')

In [88]:
inp = ['SI','EI','MI','MI','1/MI','EI','SI','MI','1/SI','1/SI','1/MI','1/VSI','MI','MI','SI','VSI','VSI','EI','SI','MI','1/SI','1/SI','1/MI','1/SI','1/VSI','1/MI','1/SI','1/SI','MI','EI','1/SI','MI','SI','MI','MI','EI','MI','1/SI','EI','EI','MI','1/SI','SI','EI','AI','MI','SI','MI','MI','MI','SI','MI','MI','SI','SI','SI','MI','EI','MI','MI']

In [89]:
k=0 # Implementing ANP for Sub-criteria v/s Sub-criteria sets
for i in range(1,13,2):
    for j in range(i+2,13):
        l1=inp[k]
        l2=inp[k+1]
        x1=anp_term[l1.upper()]
        x2=anp_term[l2.upper()]
        p1=opt*x1[2]+(1-opt)*x1[0]
        p2=opt*x2[2]+(1-opt)*x2[0]
        sm.iloc[i][j]=p1
        sm.iloc[i+1][j]=p2
        k+=2       
sm

Goal C11 C12  C21 C22       C31       C32       C41       C42       C51  \
Goal    0   0   0    0   0         0         0         0         0         0   
C11     0   0   0    5   3     0.375         5  0.208333     0.375         3   
C12     0   0   0  1.5   3       1.5         3  0.208333  0.145833         3   
C21     0   0   0    0   0  0.208333     0.375  0.145833  0.208333         3   
C22     0   0   0    0   0  0.208333  0.208333     0.375  0.208333       1.5   
C31     0   0   0    0   0         0         0         3       1.5         3   
C32     0   0   0    0   0         0         0  0.208333       1.5  0.208333   
C41     0   0   0    0   0         0         0         0         0         3   
C42     0   0   0    0   0         0         0         0         0         3   
C51     0   0   0    0   0         0         0         0         0         0   
C52     0   0   0    0   0         0         0         0         0         0   
C61     0   0   0    0   0         0         0         0         0         0   
C62     0   0   0    0   0         0         0         0         0         0   
C1      0   0   0    0   0         0         0         0         0         0   
C2      0   0   0    0   0         0         0         0         0         0   
C3      0   0   0    0   0         0         0         0         0         0   
C4      0   0   0    0   0         0         0         0         0         0   
C5      0   0   0    0   0         0         0         0         0         0   
C6      0   0   0    0   0         0         0         0         0         0   

           C52  C61  C62 C1 C2 C3 C4 C5 C6  
Goal         0    0    0  0  0  0  0  0  0  
C11          5    7    5  0  0  0  0  0  0  
C12          7  1.5    3  0  0  0  0  0  0  
C21   0.208333    5    3  0  0  0  0  0  0  
C22          3    3  1.5  0  0  0  0  0  0  
C31          5  8.5    5  0  0  0  0  0  0  
C32        1.5    3    3  0  0  0  0  0  0  
C41          5    3    5  0  0  0  0  0  0  
C42          3    5    5  0  0  0  0  0  0  
C51          0    3    3  0  0  0  0  0  0  
C52          0  1.5    3  0  0  0  0  0  0  
C61          0    0    0  0  0  0  0  0  0  
C62          0    0    0  0  0  0  0  0  0  
C1           0    0    0  0  0  0  0  0  0  
C2           0    0    0  0  0  0  0  0  0  
C3           0    0    0  0  0  0  0  0  0  
C4           0    0    0  0  0  0  0  0  0  
C5           0    0    0  0  0  0  0  0  0  
C6           0    0    0  0  0  0  0  0  0

In [90]:
for i in range(1,13,2):
    for j in range(3,13):
        if(sm.iloc[i][j]!=0):
            tot=sm.iloc[i][j]+sm.iloc[i+1][j]
            #print(i,j,tot)
            sm.iloc[i][j]=sm.iloc[i][j]/tot
            sm.iloc[i+1][j]=sm.iloc[i+1][j]/tot
        else:
            continue
sm

Goal C11 C12       C21  C22  C31       C32        C41   C42        C51  \
Goal    0   0   0         0    0    0         0          0     0          0   
C11     0   0   0  0.769231  0.5  0.2     0.625        0.5  0.72        0.5   
C12     0   0   0  0.230769  0.5  0.8     0.375        0.5  0.28        0.5   
C21     0   0   0         0    0  0.5  0.642857       0.28   0.5   0.666667   
C22     0   0   0         0    0  0.5  0.357143       0.72   0.5   0.333333   
C31     0   0   0         0    0    0         0   0.935065   0.5   0.935065   
C32     0   0   0         0    0    0         0  0.0649351   0.5  0.0649351   
C41     0   0   0         0    0    0         0          0     0        0.5   
C42     0   0   0         0    0    0         0          0     0        0.5   
C51     0   0   0         0    0    0         0          0     0          0   
C52     0   0   0         0    0    0         0          0     0          0   
C61     0   0   0         0    0    0         0          0     0          0   
C62     0   0   0         0    0    0         0          0     0          0   
C1      0   0   0         0    0    0         0          0     0          0   
C2      0   0   0         0    0    0         0          0     0          0   
C3      0   0   0         0    0    0         0          0     0          0   
C4      0   0   0         0    0    0         0          0     0          0   
C5      0   0   0         0    0    0         0          0     0          0   
C6      0   0   0         0    0    0         0          0     0          0   

            C52       C61       C62 C1 C2 C3 C4 C5 C6  
Goal          0         0         0  0  0  0  0  0  0  
C11    0.416667  0.823529     0.625  0  0  0  0  0  0  
C12    0.583333  0.176471     0.375  0  0  0  0  0  0  
C21   0.0649351     0.625  0.666667  0  0  0  0  0  0  
C22    0.935065     0.375  0.333333  0  0  0  0  0  0  
C31    0.769231   0.73913     0.625  0  0  0  0  0  0  
C32    0.230769   0.26087     0.375  0  0  0  0  0  0  
C41       0.625     0.375       0.5  0  0  0  0  0  0  
C42       0.375     0.625       0.5  0  0  0  0  0  0  
C51           0  0.666667       0.5  0  0  0  0  0  0  
C52           0  0.333333       0.5  0  0  0  0  0  0  
C61           0         0         0  0  0  0  0  0  0  
C62           0         0         0  0  0  0  0  0  0  
C1            0         0         0  0  0  0  0  0  0  
C2            0         0         0  0  0  0  0  0  0  
C3            0         0         0  0  0  0  0  0  0  
C4            0         0         0  0  0  0  0  0  0  
C5            0         0         0  0  0  0  0  0  0  
C6            0         0         0  0  0  0  0  0  0

In [91]:
k=1 # Appending DEMATEL weights in supermatrix
for i in range(len(dematel_weights)):
    j=0
    sm.iloc[k][k+j]=dematel_weights[i][j][0]
    sm.iloc[k][k+j+1]=dematel_weights[i][j][1]
    sm.iloc[k+1][k+j]=dematel_weights[i][j+1][0]
    sm.iloc[k+1][k+j+1]=dematel_weights[i][j+1][1]
    k+=2
for i in range(13,19):
    sm.iloc[i][0]=priority_vector[i-13]
sm

Goal       C11       C12       C21       C22        C31       C32  \
Goal          0         0         0         0         0          0         0   
C11           0  0.349515  0.532468  0.769231       0.5        0.2     0.625   
C12           0  0.650485  0.467532  0.230769       0.5        0.8     0.375   
C21           0         0         0  0.497666  0.765279        0.5  0.642857   
C22           0         0         0  0.502334  0.234721        0.5  0.357143   
C31           0         0         0         0         0  0.0645161       0.5   
C32           0         0         0         0         0   0.935484       0.5   
C41           0         0         0         0         0          0         0   
C42           0         0         0         0         0          0         0   
C51           0         0         0         0         0          0         0   
C52           0         0         0         0         0          0         0   
C61           0         0         0         0         0          0         0   
C62           0         0         0         0         0          0         0   
C1     0.355305         0         0         0         0          0         0   
C2     0.250936         0         0         0         0          0         0   
C3     0.141455         0         0         0         0          0         0   
C4     0.174967         0         0         0         0          0         0   
C5    0.0443272         0         0         0         0          0         0   
C6    0.0330105         0         0         0         0          0         0   

            C41       C42        C51        C52       C61       C62 C1 C2 C3  \
Goal          0         0          0          0         0         0  0  0  0   
C11         0.5      0.72        0.5   0.416667  0.823529     0.625  0  0  0   
C12         0.5      0.28        0.5   0.583333  0.176471     0.375  0  0  0   
C21        0.28       0.5   0.666667  0.0649351     0.625  0.666667  0  0  0   
C22        0.72       0.5   0.333333   0.935065     0.375  0.333333  0  0  0   
C31    0.935065       0.5   0.935065   0.769231   0.73913     0.625  0  0  0   
C32   0.0649351       0.5  0.0649351   0.230769   0.26087     0.375  0  0  0   
C41    0.234721  0.502334        0.5      0.625     0.375       0.5  0  0  0   
C42    0.765279  0.497666        0.5      0.375     0.625       0.5  0  0  0   
C51           0         0    0.47353   0.718622  0.666667       0.5  0  0  0   
C52           0         0    0.52647   0.281378  0.333333       0.5  0  0  0   
C61           0         0          0          0  0.432729  0.524296  0  0  0   
C62           0         0          0          0  0.567271  0.475704  0  0  0   
C1            0         0          0          0         0         0  0  0  0   
C2            0         0          0          0         0         0  0  0  0   
C3            0         0          0          0         0         0  0  0  0   
C4            0         0          0          0         0         0  0  0  0   
C5            0         0          0          0         0         0  0  0  0   
C6            0         0          0          0         0         0  0  0  0   

     C4 C5 C6  
Goal  0  0  0  
C11   0  0  0  
C12   0  0  0  
C21   0  0  0  
C22   0  0  0  
C31   0  0  0  
C32   0  0  0  
C41   0  0  0  
C42   0  0  0  
C51   0  0  0  
C52   0  0  0  
C61   0  0  0  
C62   0  0  0  
C1    0  0  0  
C2    0  0  0  
C3    0  0  0  
C4    0  0  0  
C5    0  0  0  
C6    0  0  0

In [92]:
for i in range(13,19): # Appending Normalized Relative Weight of Criteria v/s Criteria to Supermatrix
    for j in range(13,19):
        sm.iloc[i][j]=nor_matrix.iloc[i-13][j-13]
sm

Goal       C11       C12       C21       C22        C31       C32  \
Goal          0         0         0         0         0          0         0   
C11           0  0.349515  0.532468  0.769231       0.5        0.2     0.625   
C12           0  0.650485  0.467532  0.230769       0.5        0.8     0.375   
C21           0         0         0  0.497666  0.765279        0.5  0.642857   
C22           0         0         0  0.502334  0.234721        0.5  0.357143   
C31           0         0         0         0         0  0.0645161       0.5   
C32           0         0         0         0         0   0.935484       0.5   
C41           0         0         0         0         0          0         0   
C42           0         0         0         0         0          0         0   
C51           0         0         0         0         0          0         0   
C52           0         0         0         0         0          0         0   
C61           0         0         0         0         0          0         0   
C62           0         0         0         0         0          0         0   
C1     0.355305         0         0         0         0          0         0   
C2     0.250936         0         0         0         0          0         0   
C3     0.141455         0         0         0         0          0         0   
C4     0.174967         0         0         0         0          0         0   
C5    0.0443272         0         0         0         0          0         0   
C6    0.0330105         0         0         0         0          0         0   

            C41       C42        C51        C52       C61       C62  \
Goal          0         0          0          0         0         0   
C11         0.5      0.72        0.5   0.416667  0.823529     0.625   
C12         0.5      0.28        0.5   0.583333  0.176471     0.375   
C21        0.28       0.5   0.666667  0.0649351     0.625  0.666667   
C22        0.72       0.5   0.333333   0.935065     0.375  0.333333   
C31    0.935065       0.5   0.935065   0.769231   0.73913     0.625   
C32   0.0649351       0.5  0.0649351   0.230769   0.26087     0.375   
C41    0.234721  0.502334        0.5      0.625     0.375       0.5   
C42    0.765279  0.497666        0.5      0.375     0.625       0.5   
C51           0         0    0.47353   0.718622  0.666667       0.5   
C52           0         0    0.52647   0.281378  0.333333       0.5   
C61           0         0          0          0  0.432729  0.524296   
C62           0         0          0          0  0.567271  0.475704   
C1            0         0          0          0         0         0   
C2            0         0          0          0         0         0   
C3            0         0          0          0         0         0   
C4            0         0          0          0         0         0   
C5            0         0          0          0         0         0   
C6            0         0          0          0         0         0   

             C1         C2     C3         C4         C5         C6  
Goal          0          0      0          0          0          0  
C11           0          0      0          0          0          0  
C12           0          0      0          0          0          0  
C21           0          0      0          0          0          0  
C22           0          0      0          0          0          0  
C31           0          0      0          0          0          0  
C32           0          0      0          0          0          0  
C41           0          0      0          0          0          0  
C42           0          0      0          0          0          0  
C51           0          0      0          0          0          0  
C52           0          0      0          0          0          0  
C61           0          0      0          0          0          0  
C62           0          0      0          0          0          0  
C1     0.361809   0.580

In [93]:
inp1 = ['NA','NA','SI','VSI','MI','SI','EI','MI','SI','VSI','AI','VSI',
	'1/EI','1/MI','NA','NA','SI','SI','MI','SI','VSI','SI','VSI','AI',
	'1/MI','1/MI','1/EI','1/EI','NA','NA','SI','MI','VSI','VSI','SI','VSI',
	'1/SI','1/MI','1/EI','1/MI','1/EI','1/EI','NA','NA','SI','VSI','AI','AI',
	'1/SI','1/VSI','1/VSI','1/SI','1/VSI','1/VSI','1/SI','1/VSI','NA','NA','MI','SI',
	'1/AI','1/VSI','1/VSI','1/AI','1/SI','1/VSI','1/AI','1/AI','1/MI','1/SI','NA','NA']
k=0 # Providing input for Fuzzy ANP for Criteria v/s Sub-criteria
for i in range(13,19):
    for j in range(1,13):
        l=inp1[k]
        x=anp_term[l.upper()]
        y=opt*x[2]+(1-opt)*x[0]
        sm.iloc[i][j]=y
        k+=1
sm

Goal       C11       C12       C21       C22        C31       C32  \
Goal          0         0         0         0         0          0         0   
C11           0  0.349515  0.532468  0.769231       0.5        0.2     0.625   
C12           0  0.650485  0.467532  0.230769       0.5        0.8     0.375   
C21           0         0         0  0.497666  0.765279        0.5  0.642857   
C22           0         0         0  0.502334  0.234721        0.5  0.357143   
C31           0         0         0         0         0  0.0645161       0.5   
C32           0         0         0         0         0   0.935484       0.5   
C41           0         0         0         0         0          0         0   
C42           0         0         0         0         0          0         0   
C51           0         0         0         0         0          0         0   
C52           0         0         0         0         0          0         0   
C61           0         0         0         0         0          0         0   
C62           0         0         0         0         0          0         0   
C1     0.355305         0         0         5         7          3         5   
C2     0.250936      0.75     0.375         0         0          5         5   
C3     0.141455     0.375     0.375      0.75      0.75          0         0   
C4     0.174967  0.208333     0.375      0.75     0.375       0.75      0.75   
C5    0.0443272  0.208333  0.145833  0.145833  0.208333   0.145833  0.145833   
C6    0.0330105  0.118056  0.145833  0.145833  0.118056   0.208333  0.145833   

            C41       C42        C51        C52       C61       C62  \
Goal          0         0          0          0         0         0   
C11         0.5      0.72        0.5   0.416667  0.823529     0.625   
C12         0.5      0.28        0.5   0.583333  0.176471     0.375   
C21        0.28       0.5   0.666667  0.0649351     0.625  0.666667   
C22        0.72       0.5   0.333333   0.935065     0.375  0.333333   
C31    0.935065       0.5   0.935065   0.769231   0.73913     0.625   
C32   0.0649351       0.5  0.0649351   0.230769   0.26087     0.375   
C41    0.234721  0.502334        0.5      0.625     0.375       0.5   
C42    0.765279  0.497666        0.5      0.375     0.625       0.5   
C51           0         0    0.47353   0.718622  0.666667       0.5   
C52           0         0    0.52647   0.281378  0.333333       0.5   
C61           0         0          0          0  0.432729  0.524296   
C62           0         0          0          0  0.567271  0.475704   
C1          1.5         3          5          7       8.5         7   
C2            3         5          7          5         7       8.5   
C3            5         3          7          7         5         7   
C4            0         0          5          7       8.5       8.5   
C5     0.208333  0.145833          0          0         3         5   
C6     0.118056  0.118056      0.375   0.208333         0         0   

             C1         C2     C3         C4         C5         C6  
Goal          0          0      0          0          0          0  
C11           0          0      0          0          0          0  
C12           0          0      0          0          0          0  
C21           0          0      0          0          0          0  
C22           0          0      0          0          0          0  
C31           0          0      0          0          0          0  
C32           0          0      0          0          0          0  
C41           0          0      0          0          0          0  
C42           0          0      0          0          0          0  
C51           0          0      0          0          0          0  
C52           0          0      0          0          0          0  
C61           0          0      0          0          0          0  
C62           0          0      0          0          0          0  
C1     0.361809   0.580

In [94]:
for i in range(1,13): # Performing computation steps of Fuzzy ANP for Critera v/s Sub-Criteria sets
    tot=0
    for j in range(13,19):
        tot+=sm.iloc[j][i]
    for j in range(13,19):
        sm.iloc[j][i]=sm.iloc[j][i]/tot
sm

Goal        C11       C12        C21        C22        C31  \
Goal          0          0         0          0          0          0   
C11           0   0.349515  0.532468   0.769231        0.5        0.2   
C12           0   0.650485  0.467532   0.230769        0.5        0.8   
C21           0          0         0   0.497666   0.765279        0.5   
C22           0          0         0   0.502334   0.234721        0.5   
C31           0          0         0          0          0  0.0645161   
C32           0          0         0          0          0   0.935484   
C41           0          0         0          0          0          0   
C42           0          0         0          0          0          0   
C51           0          0         0          0          0          0   
C52           0          0         0          0          0          0   
C61           0          0         0          0          0          0   
C62           0          0         0          0          0          0   
C1     0.355305          0         0   0.736196   0.828266   0.329519   
C2     0.250936   0.451883  0.264706          0          0   0.549199   
C3     0.141455   0.225941  0.264706   0.110429  0.0887428          0   
C4     0.174967   0.125523  0.264706   0.110429  0.0443714  0.0823799   
C5    0.0443272   0.125523  0.102941  0.0214724  0.0246508  0.0160183   
C6    0.0330105  0.0711297  0.102941  0.0214724  0.0139688  0.0228833   

            C32        C41        C42        C51         C52       C61  \
Goal          0          0          0          0           0         0   
C11       0.625        0.5       0.72        0.5    0.416667  0.823529   
C12       0.375        0.5       0.28        0.5    0.583333  0.176471   
C21    0.642857       0.28        0.5   0.666667   0.0649351     0.625   
C22    0.357143       0.72        0.5   0.333333    0.935065     0.375   
C31         0.5   0.935065        0.5   0.935065    0.769231   0.73913   
C32         0.5  0.0649351        0.5  0.0649351    0.230769   0.26087   
C41           0   0.234721   0.502334        0.5       0.625     0.375   
C42           0   0.765279   0.497666        0.5       0.375     0.625   
C51           0          0          0    0.47353    0.718622  0.666667   
C52           0          0          0    0.52647    0.281378  0.333333   
C61           0          0          0          0           0  0.432729   
C62           0          0          0          0           0  0.567271   
C1      0.45283    0.15265   0.266338   0.205128    0.267091  0.265625   
C2      0.45283     0.3053   0.443896   0.287179    0.190779   0.21875   
C3            0   0.508834   0.266338   0.287179    0.267091   0.15625   
C4    0.0679245          0          0   0.205128    0.267091  0.265625   
C5    0.0132075  0.0212014   0.012947          0           0   0.09375   
C6    0.0132075  0.0120141  0.0104809  0.0153846  0.00794913         0   

           C62         C1         C2     C3         C4         C5         C6  
Goal         0          0          0      0          0          0          0  
C11      0.625          0          0      0          0          0          0  
C12      0.375          0          0      0          0          0          0  
C21   0.666667          0          0      0          0          0          0  
C22   0.333333          0          0      0          0          0          0  
C31      0.625          0          0      0          0          0          0  
C32      0.375          0          0      0          0          0          0  
C41        0.5          0          0      0          0          0          0  
C42        0.5          0          0      0          0          0          0  
C51        0.5          0          0      0          0          0          0  
C52        0.5          0          0      0          0          0          0  
C61   0.524296          0          0      0          0          0          0  
C62   0.475704          0          0      

In [95]:
tot=sm.sum(axis=0) # Normalizing entire supermatrix to obtain weighted supermatrix
w_sm=sm.copy()
for i in range(0,19):
    for j in range(0,19):
        w_sm.iloc[j][i]=sm.iloc[j][i]/tot[i]
w_sm

Goal        C11        C12         C21         C22         C31  \
Goal          0          0          0           0           0           0   
C11           0   0.174757   0.266234     0.25641    0.166667        0.05   
C12           0   0.325243   0.233766   0.0769231    0.166667         0.2   
C21           0          0          0    0.165889    0.255093       0.125   
C22           0          0          0    0.167445   0.0782402       0.125   
C31           0          0          0           0           0    0.016129   
C32           0          0          0           0           0    0.233871   
C41           0          0          0           0           0           0   
C42           0          0          0           0           0           0   
C51           0          0          0           0           0           0   
C52           0          0          0           0           0           0   
C61           0          0          0           0           0           0   
C62           0          0          0           0           0           0   
C1     0.355305          0          0    0.245399    0.276089   0.0823799   
C2     0.250936   0.225941   0.132353           0           0      0.1373   
C3     0.141455   0.112971   0.132353   0.0368098   0.0295809           0   
C4     0.174967  0.0627615   0.132353   0.0368098   0.0147905    0.020595   
C5    0.0443272  0.0627615  0.0514706  0.00715746  0.00821693  0.00400458   
C6    0.0330105  0.0355649  0.0514706  0.00715746  0.00465626  0.00572082   

             C32         C41         C42        C51         C52        C61  \
Goal           0           0           0          0           0          0   
C11      0.15625         0.1       0.144  0.0833333   0.0694444   0.117647   
C12      0.09375         0.1       0.056  0.0833333   0.0972222  0.0252101   
C21     0.160714       0.056         0.1   0.111111   0.0108225  0.0892857   
C22    0.0892857       0.144         0.1  0.0555556    0.155844  0.0535714   
C31        0.125    0.187013         0.1   0.155844    0.128205    0.10559   
C32        0.125    0.012987         0.1  0.0108225   0.0384615  0.0372671   
C41            0   0.0469441    0.100467  0.0833333    0.104167  0.0535714   
C42            0    0.153056   0.0995332  0.0833333      0.0625  0.0892857   
C51            0           0           0  0.0789217     0.11977  0.0952381   
C52            0           0           0   0.087745   0.0468964   0.047619   
C61            0           0           0          0           0  0.0618185   
C62            0           0           0          0           0  0.0810386   
C1      0.113208     0.03053   0.0532676   0.034188   0.0445151  0.0379464   
C2      0.113208   0.0610601   0.0887793  0.0478632   0.0317965    0.03125   
C3             0    0.101767   0.0532676  0.0478632   0.0445151  0.0223214   
C4     0.0169811           0           0   0.034188   0.0445151  0.0379464   
C5    0.00330189  0.00424028   0.0025894          0           0  0.0133929   
C6    0.00330189  0.00240283  0.00209618  0.0025641  0.00132485          0   

            C62         C1         C2     C3         C4         C5         C6  
Goal          0          0          0      0          0          0          0  
C11   0.0892857          0          0      0          0          0          0  
C12   0.0535714          0          0      0          0          0          0  
C21   0.0952381          0          0      0          0          0          0  
C22    0.047619          0          0      0          0          0          0  
C31   0.0892857          0          0      0          0          0          0  
C32   0.0535714          0          0      0          0          0          0  
C41   0.0714286          0          0      0          0          0          0  
C42   0.0714286          0          0      0          0          0          0  
C51   0.0714286          0          0      0          0          0          0  
C52   0.0714286          0   

In [96]:
w_sm_arr=w_sm.to_numpy(dtype=float) # Raising supermatrix to limiting power to obtain criteria weights
l_sm=pd.DataFrame(np.linalg.matrix_power(w_sm_arr,17),columns=col,index=col)
l_sm=l_sm.round(4)
l_sm
criteria_weights=list(l_sm.iloc[13:19,0])
l_sm

Goal     C11     C12     C21     C22     C31     C32     C41     C42  \
Goal  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C11   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C12   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C21   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C22   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C31   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C32   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C41   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C42   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C51   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C52   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C61   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C62   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C1    0.3809  0.3809  0.3809  0.3809  0.3809  0.3809  0.3809  0.3809  0.3809   
C2    0.2321  0.2321  0.2321  0.2321  0.2321  0.2321  0.2321  0.2321  0.2321   
C3    0.1325  0.1325  0.1325  0.1325  0.1325  0.1325  0.1325  0.1325  0.1325   
C4    0.1749  0.1749  0.1749  0.1749  0.1749  0.1749  0.1749  0.1749  0.1749   
C5    0.0443  0.0443  0.0443  0.0443  0.0443  0.0443  0.0443  0.0443  0.0443   
C6    0.0352  0.0352  0.0352  0.0352  0.0352  0.0352  0.0352  0.0352  0.0352   

         C51     C52     C61     C62      C1      C2      C3      C4      C5  \
Goal  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C11   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C12   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C21   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C22   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C31   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C32   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C41   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C42   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C51   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C52   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C61   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C62   0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
C1    0.3809  0.3809  0.3809  0.3809  0.3809  0.3809  0.3809  0.3809  0.3809   
C2    0.2321  0.2321  0.2321  0.2321  0.2321  0.2321  0.2321  0.2321  0.2321   
C3    0.1325  0.1325  0.1325  0.1325  0.1325  0.1325  0.1325  0.1325  0.1325   
C4    0.1749  0.1749  0.1749  0.1749  0.1749  0.1749  0.1749  0.1749  0.1749   
C5    0.0443  0.0443  0.0443  0.0443  0.0443  0.0443  0.0443  0.0443  0.0443   
C6    0.0352  0.0352  0.0352  0.0352  0.0352  0.0352  0.0352  0.0352  0.0352   

          C6  
Goal  0.0000  
C11   0.0000  
C12   0.0000  
C21   0.0000  
C22   0.0000  
C31   0.0000  
C32   0.0000  
C41   0.0000  
C42   0.0000  
C51   0.0000  
C52   0.0000  
C61   0.0000  
C62   0.0000  
C1    0.3809  
C2    0.2321  
C3    0.1325  
C4    0.1749  
C5    0.0443  
C6    0.0352

In [97]:
criteria_weights

[0.3809, 0.2321, 0.1325, 0.1749, 0.0443, 0.0352]

In [48]:
def wsc(l): # Defining functions for Fuzzy VIKOR Calculations
    minimum=1
    for j in l:
        x=j[0]
        if(x<minimum):
            minimum=x
    maximum=0
    for j in l:
        x=j[2]
        if(x>maximum):
            maximum=x
    average,x=0,0
    for j in l:
        x+=j[1]
    average=x/len(l)
    result=[minimum,average,maximum]
    return(result)

def min_value(l):
    result=[]
    for i in range(0,3):
        minimum=10
        for j in l:
            x=j[i]
            if(x<minimum):
                minimum=x
        result.append(minimum)
    return(result)

def max_value(l):
    result=[]
    for i in range(0,3):
        maximum=0
        for j in l:
            x=j[i]
            if(x>maximum):
                maximum=x
        result.append(maximum)
    return(result)
def da_sc(l1,l2):
    da_sc=[]
    dif=l2[0][2]-l2[1][0]
    for j in range(len(l1)):
        x=[]
        for k in range(3):
            x.append((l2[0][k]-l1[j][-(k+1)])/dif)
        da_sc.append(x)
    return(da_sc)
def w_da(l1,l2):
    result=[]
    for j in l2:
        for k in range(len(l1)):
            result.append(l1[k]*j[k])
    return(result)

In [67]:
vikor_weights=[] # Reading input for VIKOR and performing computation in order to obtain VIKOR weights
for i in criteria.values():
    val1,val2,wsc1,wsc2=[],[],[],[]
    l1=list(input(f'Enter ratings by decision makers wrt {i[0]}: ').split())
    l2=list(input(f'Enter ratings by decision makers wrt {i[1]}: ').split())
    for j in range(len(l1)):
        val1.append(lin_term_vikor[l1[j].upper()])
    for j in range(len(l2)):
        val2.append(lin_term_vikor[l2[j].upper()])
    wsc1=wsc(val1)
    wsc2=wsc(val2)
    l1,l2=[],[]
    for j in alternatives:
        x=int(input(f'Enter ratings of {i[0]} with respect to {j}: '))-1
        l1.append(lin_term_anp[x])
        x=int(input(f'Enter ratings of {i[1]} with respect to {j}: '))-1
        l2.append(lin_term_anp[x])
    sc1_f,sc2_f=[],[]
    sc1_f.append(list(max_value(l1)))
    sc1_f.append(list(min_value(l1)))
    sc2_f.append(list(max_value(l2)))
    sc2_f.append(list(min_value(l2)))
    da_sc1=da_sc(l1,sc1_f)
    da_sc2=da_sc(l2,sc2_f)
    w_da1=w_da(wsc1,da_sc1)
    w_da2=w_da(wsc2,da_sc2)
    s_j,r_j=[],[]
    for j in range(len(w_da1)):
        s_j.append(w_da1[j]+w_da2[j])
        r_j.append(max(w_da1[j],w_da2[j])) 
    s_star,r_star=[],[]
    for j in range(3):
        x1,x2=[],[]
        k=j
        while(k<len(s_j)):
            x1.append(s_j[k])
            x2.append(r_j[k])
            k+=3
        if(j==2):
            s_oc=max(x1)
            r_oc=max(x2)
        s_star.append(min(x1))
        r_star.append(min(x2))
    q=[]
    for j in range(len(s_j)):
        x=0.5*(s_j[j]-s_star[-(j%3+1)])/(s_oc-s_star[0])+(1-0.5*(r_j[j]-r_star[-(j%3+1)])/(r_oc-r_star[0]))
        q.append(round(x,4))
    defuzzified_weights=[]
    j=0
    while(j<len(q)):
        x=(q[j]+4*q[j+1]+q[j+2])/6
        defuzzified_weights.append(round(x,4))
        j+=3
    vikor_weights.append(defuzzified_weights)
vikor_weights   

Enter ratings by decision makers wrt Mass Energy Density: mh i vh
Enter ratings by decision makers wrt Volume Energy Density: vh vh i
Enter ratings of Mass Energy Density with respect to Electrochemical: 6
Enter ratings of Volume Energy Density with respect to Electrochemical: 7
Enter ratings of Mass Energy Density with respect to Electrical: 8
Enter ratings of Volume Energy Density with respect to Electrical: 9
Enter ratings of Mass Energy Density with respect to Magnetic: 9
Enter ratings of Volume Energy Density with respect to Magnetic: 9
Enter ratings of Mass Energy Density with respect to Mechanical: 1
Enter ratings of Volume Energy Density with respect to Mechanical: 3
Enter ratings of Mass Energy Density with respect to Chemical: 8
Enter ratings of Volume Energy Density with respect to Chemical: 7
Enter ratings by decision makers wrt Number of discharge cycles: m vh mh
Enter ratings by decision makers wrt Shelf life: mh m m
Enter ratings of Number of discharge cycles with respec

[[0.9866, 0.9805, 1.0, 0.9862, 0.9682],
 [1.028, 0.9937, 1.0, 0.9774, 0.9723],
 [1.0004, 0.9688, 1.0, 1.0006, 0.9955],
 [0.9044, 0.9045, 0.9319, 1.0, 0.9995],
 [0.9995, 0.9917, 0.9992, 1.0, 0.9992],
 [0.9815, 1.0, 0.9882, 0.9585, 0.9952]]

In [132]:
vikor_rank=vikor_weights[:6]
vikor_rank=np.transpose(np.array(vikor_rank))
#vikor_rank=np.append(vikor_rank,criteria_weights)
vikor_rank

array([[0.9866, 1.028 , 1.0004, 0.9044, 0.9995, 0.9815],
       [0.9805, 0.9937, 0.9688, 0.9045, 0.9917, 1.    ],
       [1.    , 1.    , 1.    , 0.9319, 0.9992, 0.9882],
       [0.9862, 0.9774, 1.0006, 1.    , 1.    , 0.9585],
       [0.9682, 0.9723, 0.9955, 0.9995, 0.9992, 0.9952]])

In [164]:
final_vikor_weights=vikor_rank
final_rankings=pd.DataFrame(final_vikor_weights,columns=main_criteria,index=alternatives)

In [165]:
final_rankings

Energy Density  Life Cycles  Cycle efficiency  \
Electrochemical          0.9866       1.0280            1.0004   
Electrical               0.9805       0.9937            0.9688   
Magnetic                 1.0000       1.0000            1.0000   
Mechanical               0.9862       0.9774            1.0006   
Chemical                 0.9682       0.9723            0.9955   

                 Investment Level  Suitability to climatic conditions  \
Electrochemical            0.9044                              0.9995   
Electrical                 0.9045                              0.9917   
Magnetic                   0.9319                              0.9992   
Mechanical                 1.0000                              1.0000   
Chemical                   0.9995                              0.9992   

                 Space required  
Electrochemical          0.9815  
Electrical               1.0000  
Magnetic                 0.9882  
Mechanical               0.9585  
Chemical                 0.9952

In [166]:
criteria_weights

[0.3809, 0.2321, 0.1325, 0.1749, 0.0443, 0.0352]

In [174]:
final_sum=[] # Obtaining product of Q values with criteria weights to obtain final values for alternative ranking
for i in range(5):
    x=0
    for j in range(6):
        x+=criteria_weights[j]*final_rankings.iloc[i][j]
    final_sum.append(x)
final_sum

[0.9839539500000001, 0.96980558, 0.98753851, 0.98801682, 0.98047011]

In [175]:
final_rankings['Weights']=final_sum

In [177]:
final_rankings.round(4)

Energy Density  Life Cycles  Cycle efficiency  \
Electrochemical          0.9866       1.0280            1.0004   
Electrical               0.9805       0.9937            0.9688   
Magnetic                 1.0000       1.0000            1.0000   
Mechanical               0.9862       0.9774            1.0006   
Chemical                 0.9682       0.9723            0.9955   

                 Investment Level  Suitability to climatic conditions  \
Electrochemical            0.9044                              0.9995   
Electrical                 0.9045                              0.9917   
Magnetic                   0.9319                              0.9992   
Mechanical                 1.0000                              1.0000   
Chemical                   0.9995                              0.9992   

                 Space required  Weights  
Electrochemical          0.9815   0.9840  
Electrical               1.0000   0.9698  
Magnetic                 0.9882   0.9875  
Mechanical               0.9585   0.9880  
Chemical                 0.9952   0.9805

In [179]:
result=final_rankings.sort_values(by='Weights') # Ranking alternatives

In [180]:
result

Energy Density  Life Cycles  Cycle efficiency  \
Electrical               0.9805       0.9937            0.9688   
Chemical                 0.9682       0.9723            0.9955   
Electrochemical          0.9866       1.0280            1.0004   
Magnetic                 1.0000       1.0000            1.0000   
Mechanical               0.9862       0.9774            1.0006   

                 Investment Level  Suitability to climatic conditions  \
Electrical                 0.9045                              0.9917   
Chemical                   0.9995                              0.9992   
Electrochemical            0.9044                              0.9995   
Magnetic                   0.9319                              0.9992   
Mechanical                 1.0000                              1.0000   

                 Space required   Weights  
Electrical               1.0000  0.969806  
Chemical                 0.9952  0.980470  
Electrochemical          0.9815  0.983954  
Magnetic                 0.9882  0.987539  
Mechanical               0.9585  0.988017